name: Monitor API

on:
  schedule:
    - cron: "7,22,37,52 * * * *"

  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm ci

      - name: Run Monitor
        run: node index.js
        env:
          pass: ${{ secrets.APP_PASSWORD }} # repo secret
